# Generated by Django 5.1.5 on 2025-06-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='product',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
    ]
